name: "spring_compress"
description: Fast, efficient, lossless compression of FASTQ files.
keywords:
  - FASTQ
  - compression
  - lossless
tools:
  - "spring":
      description: "SPRING is a compression tool for Fastq files (containing up to 4.29 Billion reads)"
      homepage: "https://github.com/shubhamchandak94/Spring"
      documentation: "https://github.com/shubhamchandak94/Spring/blob/master/README.md"
      tool_dev_url: "https://github.com/shubhamchandak94/Spring"
      doi: "https://doi.org/10.1093/bioinformatics/bty1015"
      licence: "['Free for non-commercial use']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - fastq:
      type: file
      description: Either a single-end FASTQ file or paired-end files.
      pattern: "*.{fq.gz,fastq.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - spring:
      type: file
      description: One sequence file in spring compressed format.
      pattern: "*.{spring}"

authors:
  - "@xec-cm"
